// Auto-generated by admin.html — do not edit by hand.
window.NAMELIST_DATA = {
 "savedAt": "2026-08-17T03:00:10.479Z",
 "students": [
  {
   "id": "1R1-01",
   "name": "Aiden Lim",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Aiden Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R1-02",
   "name": "Brenda Koh",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Brenda Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R1-03",
   "name": "Clarissa Phua",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Clarissa Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-04",
   "name": "Darren Chua",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Darren Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-05",
   "name": "Elena Ho",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Elena Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R1-06",
   "name": "Farhan Lim",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Farhan Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R1-07",
   "name": "Grace Koh",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Grace Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-08",
   "name": "Hakim Phua",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Hakim Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R1-09",
   "name": "Iris Chua",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Iris Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R1-10",
   "name": "Jun Jie Ho",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Jun Jie Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R1-11",
   "name": "Kavya Lim",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Kavya Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-12",
   "name": "Liang Koh",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Liang Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-13",
   "name": "Mei Ling Phua",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Mei Ling Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R1-14",
   "name": "Nadia Chua",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Nadia Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R1-15",
   "name": "Owen Ho",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Owen Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R1-16",
   "name": "Priya Lim",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Priya Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-17",
   "name": "Qi Wen Koh",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Qi Wen Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R1-18",
   "name": "Ryan Phua",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Ryan Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R1-19",
   "name": "Siti Chua",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Siti Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-20",
   "name": "Timothy Ho",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Timothy Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-21",
   "name": "Uma Lim",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Uma Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R1-22",
   "name": "Vernon Koh",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Vernon Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R1-23",
   "name": "Wei Ting Phua",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Wei Ting Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-24",
   "name": "Xin Yi Chua",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Xin Yi Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R1-25",
   "name": "Yusof Ho",
   "class": "1R1",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Yusof Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R1-26",
   "name": "Zoe Lim",
   "class": "1R1",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Zoe Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R2-01",
   "name": "Aiden Ng",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Aiden Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-02",
   "name": "Brenda Kumar",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Brenda Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-03",
   "name": "Clarissa Yeo",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Clarissa Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R2-04",
   "name": "Darren Ong",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Darren Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R2-05",
   "name": "Elena Loh",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Elena Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-06",
   "name": "Farhan Ng",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Farhan Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-07",
   "name": "Grace Kumar",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Grace Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R2-08",
   "name": "Hakim Yeo",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Hakim Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R2-09",
   "name": "Iris Ong",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Iris Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-10",
   "name": "Jun Jie Loh",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Jun Jie Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R2-11",
   "name": "Kavya Ng",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Kavya Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R2-12",
   "name": "Liang Kumar",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Liang Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R2-13",
   "name": "Mei Ling Yeo",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Mei Ling Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-14",
   "name": "Nadia Ong",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Nadia Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-15",
   "name": "Owen Loh",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Owen Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R2-16",
   "name": "Priya Ng",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Priya Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R2-17",
   "name": "Qi Wen Kumar",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Qi Wen Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R2-18",
   "name": "Ryan Yeo",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Ryan Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-19",
   "name": "Siti Ong",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Siti Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R2-20",
   "name": "Timothy Loh",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Timothy Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R2-21",
   "name": "Uma Ng",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Uma Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-22",
   "name": "Vernon Kumar",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Vernon Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-23",
   "name": "Wei Ting Yeo",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Wei Ting Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R2-24",
   "name": "Xin Yi Ong",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Xin Yi Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R2-25",
   "name": "Yusof Loh",
   "class": "1R2",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Yusof Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R2-26",
   "name": "Zoe Ng",
   "class": "1R2",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Zoe Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-01",
   "name": "Aiden Chua",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Aiden Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R3-02",
   "name": "Brenda Ho",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Brenda Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R3-03",
   "name": "Clarissa Lim",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Clarissa Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-04",
   "name": "Darren Koh",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Darren Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-05",
   "name": "Elena Phua",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Elena Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R3-06",
   "name": "Farhan Chua",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Farhan Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R3-07",
   "name": "Grace Ho",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Grace Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-08",
   "name": "Hakim Lim",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Hakim Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-09",
   "name": "Iris Koh",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Iris Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R3-10",
   "name": "Jun Jie Phua",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Jun Jie Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R3-11",
   "name": "Kavya Chua",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Kavya Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-12",
   "name": "Liang Ho",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Liang Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R3-13",
   "name": "Mei Ling Lim",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Mei Ling Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R3-14",
   "name": "Nadia Koh",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Nadia Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R3-15",
   "name": "Owen Phua",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Owen Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-16",
   "name": "Priya Chua",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Priya Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-17",
   "name": "Qi Wen Ho",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Qi Wen Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R3-18",
   "name": "Ryan Lim",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Ryan Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R3-19",
   "name": "Siti Koh",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Siti Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R3-20",
   "name": "Timothy Phua",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Timothy Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-21",
   "name": "Uma Chua",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Uma Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R3-22",
   "name": "Vernon Ho",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Vernon Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R3-23",
   "name": "Wei Ting Lim",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Wei Ting Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-24",
   "name": "Xin Yi Koh",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Xin Yi Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R3-25",
   "name": "Yusof Phua",
   "class": "1R3",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Yusof Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R3-26",
   "name": "Zoe Chua",
   "class": "1R3",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Zoe Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R4-01",
   "name": "Aiden Ong",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Aiden Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-02",
   "name": "Brenda Loh",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Brenda Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-03",
   "name": "Clarissa Ng",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Clarissa Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R4-04",
   "name": "Darren Kumar",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Darren Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R4-05",
   "name": "Elena Yeo",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Elena Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-06",
   "name": "Farhan Ong",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Farhan Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-07",
   "name": "Grace Loh",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Grace Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R4-08",
   "name": "Hakim Ng",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Hakim Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R4-09",
   "name": "Iris Kumar",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Iris Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-10",
   "name": "Jun Jie Yeo",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Jun Jie Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-11",
   "name": "Kavya Ong",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Kavya Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R4-12",
   "name": "Liang Loh",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Liang Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R4-13",
   "name": "Mei Ling Ng",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Mei Ling Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-14",
   "name": "Nadia Kumar",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Nadia Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R4-15",
   "name": "Owen Yeo",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Owen Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R4-16",
   "name": "Priya Ong",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Priya Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R4-17",
   "name": "Qi Wen Loh",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Qi Wen Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-18",
   "name": "Ryan Ng",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Ryan Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-19",
   "name": "Siti Kumar",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Siti Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R4-20",
   "name": "Timothy Yeo",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Timothy Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R4-21",
   "name": "Uma Ong",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Uma Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R4-22",
   "name": "Vernon Loh",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Vernon Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-23",
   "name": "Wei Ting Ng",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Wei Ting Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R4-24",
   "name": "Xin Yi Kumar",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Xin Yi Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R4-25",
   "name": "Yusof Yeo",
   "class": "1R4",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Yusof Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R4-26",
   "name": "Zoe Ong",
   "class": "1R4",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Zoe Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-01",
   "name": "Aiden Koh",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Aiden Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R5-02",
   "name": "Brenda Phua",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Brenda Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R5-03",
   "name": "Clarissa Chua",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Clarissa Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-04",
   "name": "Darren Ho",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Darren Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-05",
   "name": "Elena Lim",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Elena Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R5-06",
   "name": "Farhan Koh",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Farhan Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R5-07",
   "name": "Grace Phua",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Grace Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-08",
   "name": "Hakim Chua",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Hakim Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-09",
   "name": "Iris Ho",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Iris Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R5-10",
   "name": "Jun Jie Lim",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Jun Jie Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R5-11",
   "name": "Kavya Koh",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Kavya Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-12",
   "name": "Liang Phua",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Liang Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-13",
   "name": "Mei Ling Chua",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Mei Ling Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R5-14",
   "name": "Nadia Ho",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Nadia Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R5-15",
   "name": "Owen Lim",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Owen Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-16",
   "name": "Priya Koh",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Priya Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R5-17",
   "name": "Qi Wen Phua",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Qi Wen Phua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R5-18",
   "name": "Ryan Chua",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Ryan Chua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R5-19",
   "name": "Siti Ho",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Siti Ho",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-20",
   "name": "Timothy Lim",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Timothy Lim",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-21",
   "name": "Uma Koh",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Uma Koh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R5-22",
   "name": "Vernon Phua",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Vernon Phua",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R5-23",
   "name": "Wei Ting Chua",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Wei Ting Chua",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R5-24",
   "name": "Xin Yi Ho",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Xin Yi Ho",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R5-25",
   "name": "Yusof Lim",
   "class": "1R5",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Yusof Lim",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R5-26",
   "name": "Zoe Koh",
   "class": "1R5",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Zoe Koh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R6-01",
   "name": "Aiden Kumar",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Aiden Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-02",
   "name": "Brenda Yeo",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Brenda Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-03",
   "name": "Clarissa Ong",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Clarissa Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R6-04",
   "name": "Darren Loh",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Darren Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R6-05",
   "name": "Elena Ng",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Elena Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-06",
   "name": "Farhan Kumar",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Farhan Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-07",
   "name": "Grace Yeo",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Grace Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R6-08",
   "name": "Hakim Ong",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Hakim Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R6-09",
   "name": "Iris Loh",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Iris Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-10",
   "name": "Jun Jie Ng",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Jun Jie Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-11",
   "name": "Kavya Kumar",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Kavya Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R6-12",
   "name": "Liang Yeo",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Liang Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R6-13",
   "name": "Mei Ling Ong",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Mei Ling Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-14",
   "name": "Nadia Loh",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Nadia Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-15",
   "name": "Owen Ng",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Owen Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "CL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R6-16",
   "name": "Priya Kumar",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Priya Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "ML G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R6-17",
   "name": "Qi Wen Yeo",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Qi Wen Yeo",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-18",
   "name": "Ryan Ong",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Ryan Ong",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "CHINESE"
   }
  },
  {
   "id": "1R6-19",
   "name": "Siti Loh",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Siti Loh",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "ML G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R6-20",
   "name": "Timothy Ng",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Timothy Ng",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "TL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R6-21",
   "name": "Uma Kumar",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Uma Kumar",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "CL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-22",
   "name": "Vernon Yeo",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Vernon Yeo",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  },
  {
   "id": "1R6-23",
   "name": "Wei Ting Ong",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "1",
   "origin": "file",
   "sourceName": "Wei Ting Ong",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G1",
    "MT": "TL G1",
    "MA": "MA G1",
    "SCI": "SCI G1",
    "HIST": "HIST G1",
    "GEOG": "GEOG G1",
    "LIT": "LIT G1"
   }
  },
  {
   "id": "1R6-24",
   "name": "Xin Yi Loh",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "2",
   "origin": "file",
   "sourceName": "Xin Yi Loh",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G2",
    "MT": "CL G2",
    "MA": "MA G2",
    "SCI": "SCI G2",
    "HIST": "HIST G2",
    "GEOG": "GEOG G2",
    "LIT": "LIT G2"
   }
  },
  {
   "id": "1R6-25",
   "name": "Yusof Ng",
   "class": "1R6",
   "level": "1",
   "gender": "F",
   "pg": "3",
   "origin": "file",
   "sourceName": "Yusof Ng",
   "subjects": {
    "TG": "TG1",
    "EL": "EL G3",
    "MT": "ML G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3",
    "HMT": "MALAY"
   }
  },
  {
   "id": "1R6-26",
   "name": "Zoe Kumar",
   "class": "1R6",
   "level": "1",
   "gender": "M",
   "pg": "3",
   "origin": "file",
   "sourceName": "Zoe Kumar",
   "subjects": {
    "TG": "TG2",
    "EL": "EL G3",
    "MT": "TL G3",
    "MA": "MA G3",
    "SCI": "SCI G3",
    "HIST": "HIST G3",
    "GEOG": "GEOG G3",
    "LIT": "LIT G3"
   }
  }
 ],
 "groups": [
  {
   "code": "EL-1R1",
   "name": "English 1R1",
   "subject": "English Language",
   "teachers": [
    "Mrs Lim Bee Leng"
   ],
   "level": "1",
   "autoMatch": "EL=",
   "autoPg": "",
   "autoClasses": "1R1"
  },
  {
   "code": "MA-1R1",
   "name": "Mathematics 1R1",
   "subject": "Mathematics",
   "teachers": [
    "Mr Rajesh Kumar"
   ],
   "level": "1",
   "autoMatch": "MA=",
   "autoPg": "",
   "autoClasses": "1R1"
  },
  {
   "code": "EL-1R2",
   "name": "English 1R2",
   "subject": "English Language",
   "teachers": [
    "Mr Daniel Tan"
   ],
   "level": "1",
   "autoMatch": "EL=",
   "autoPg": "",
   "autoClasses": "1R2"
  },
  {
   "code": "MA-1R2",
   "name": "Mathematics 1R2",
   "subject": "Mathematics",
   "teachers": [
    "Mdm Halimah Yusof"
   ],
   "level": "1",
   "autoMatch": "MA=",
   "autoPg": "",
   "autoClasses": "1R2"
  },
  {
   "code": "EL-1R3",
   "name": "English 1R3",
   "subject": "English Language",
   "teachers": [
    "Ms Nur Aisyah"
   ],
   "level": "1",
   "autoMatch": "EL=",
   "autoPg": "",
   "autoClasses": "1R3"
  },
  {
   "code": "MA-1R3",
   "name": "Mathematics 1R3",
   "subject": "Mathematics",
   "teachers": [
    "Ms Serene Goh"
   ],
   "level": "1",
   "autoMatch": "MA=",
   "autoPg": "",
   "autoClasses": "1R3"
  },
  {
   "code": "EL-1R4",
   "name": "English 1R4",
   "subject": "English Language",
   "teachers": [
    "Mrs Grace Chua"
   ],
   "level": "1",
   "autoMatch": "EL=",
   "autoPg": "",
   "autoClasses": "1R4"
  },
  {
   "code": "MA-1R4",
   "name": "Mathematics 1R4",
   "subject": "Mathematics",
   "teachers": [
    "Mr Alvin Ong"
   ],
   "level": "1",
   "autoMatch": "MA=",
   "autoPg": "",
   "autoClasses": "1R4"
  },
  {
   "code": "EL-1R5",
   "name": "English 1R5",
   "subject": "English Language",
   "teachers": [
    "Mr Marcus Lee"
   ],
   "level": "1",
   "autoMatch": "EL=",
   "autoPg": "",
   "autoClasses": "1R5"
  },
  {
   "code": "MA-1R5",
   "name": "Mathematics 1R5",
   "subject": "Mathematics",
   "teachers": [
    "Mrs Doris Koh"
   ],
   "level": "1",
   "autoMatch": "MA=",
   "autoPg": "",
   "autoClasses": "1R5"
  },
  {
   "code": "EL-1R6",
   "name": "English 1R6",
   "subject": "English Language",
   "teachers": [
    "Mdm Sarimah Bakar"
   ],
   "level": "1",
   "autoMatch": "EL=",
   "autoPg": "",
   "autoClasses": "1R6"
  },
  {
   "code": "MA-1R6",
   "name": "Mathematics 1R6",
   "subject": "Mathematics",
   "teachers": [
    "Mr Wei Jie Chan"
   ],
   "level": "1",
   "autoMatch": "MA=",
   "autoPg": "",
   "autoClasses": "1R6"
  },
  {
   "code": "SCI-G3",
   "name": "Science G3",
   "subject": "Science",
   "teachers": [
    "Dr Sarah Loh",
    "Mr Benjamin Teo"
   ],
   "level": "1",
   "autoMatch": "SCI=SCI G3",
   "autoPg": "",
   "autoClasses": ""
  },
  {
   "code": "HIST-G3",
   "name": "History G3",
   "subject": "History",
   "teachers": [
    "Ms Priyanka Nair"
   ],
   "level": "1",
   "autoMatch": "HIST=HIST G3",
   "autoPg": "",
   "autoClasses": ""
  },
  {
   "code": "GEOG-G2",
   "name": "Geography G2",
   "subject": "Geography",
   "teachers": [
    "Mr Kenneth Sim"
   ],
   "level": "1",
   "autoMatch": "GEOG=GEOG G2",
   "autoPg": "",
   "autoClasses": ""
  },
  {
   "code": "LIT-G3",
   "name": "Literature G3",
   "subject": "Literature",
   "teachers": [
    "Mrs Evelyn Phua"
   ],
   "level": "1",
   "autoMatch": "LIT=LIT G3",
   "autoPg": "",
   "autoClasses": ""
  }
 ],
 "memberships": [
  {
   "studentId": "1R1-01",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-01",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-02",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-02",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-02",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R1-03",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-03",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-03",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-03",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-03",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-04",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-04",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-04",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-04",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-04",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-05",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-05",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-06",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-06",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-06",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R1-07",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-07",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-07",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-07",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-07",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-08",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-08",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-08",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-08",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-08",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-09",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-09",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-10",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-10",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-10",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R1-11",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-11",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-11",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-11",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-11",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-12",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-12",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-12",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-12",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-12",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-13",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-13",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-14",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-14",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-14",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R1-15",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-15",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-15",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-15",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-15",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-16",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-16",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-16",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-16",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-16",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-17",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-17",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-18",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-18",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-18",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R1-19",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-19",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-19",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-19",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-19",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-20",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-20",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-20",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-20",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-20",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-21",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-21",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-22",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-22",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-22",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R1-23",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-23",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-23",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-23",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-23",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-24",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-24",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-24",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R1-24",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R1-24",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R1-25",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-25",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-26",
   "groupCode": "EL-1R1"
  },
  {
   "studentId": "1R1-26",
   "groupCode": "MA-1R1"
  },
  {
   "studentId": "1R1-26",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-01",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-01",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-01",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-01",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-01",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-02",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-02",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-02",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-02",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-02",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-03",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-03",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-04",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-04",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-04",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-05",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-05",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-05",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-05",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-05",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-06",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-06",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-06",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-06",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-06",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-07",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-07",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-08",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-08",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-08",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-09",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-09",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-09",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-09",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-09",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-10",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-10",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-10",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-10",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-10",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-11",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-11",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-12",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-12",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-12",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-13",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-13",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-13",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-13",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-13",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-14",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-14",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-14",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-14",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-14",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-15",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-15",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-16",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-16",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-16",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-17",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-17",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-17",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-17",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-17",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-18",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-18",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-18",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-18",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-18",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-19",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-19",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-20",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-20",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-20",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-21",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-21",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-21",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-21",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-21",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-22",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-22",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-22",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-22",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-22",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-23",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-23",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-24",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-24",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-24",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R2-25",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-25",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-25",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-25",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-25",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R2-26",
   "groupCode": "EL-1R2"
  },
  {
   "studentId": "1R2-26",
   "groupCode": "MA-1R2"
  },
  {
   "studentId": "1R2-26",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R2-26",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R2-26",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-01",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-01",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-02",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-02",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-02",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R3-03",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-03",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-03",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-03",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-03",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-04",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-04",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-04",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-04",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-04",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-05",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-05",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-06",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-06",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-06",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R3-07",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-07",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-07",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-07",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-07",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-08",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-08",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-08",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-08",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-08",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-09",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-09",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-10",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-10",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-10",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R3-11",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-11",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-11",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-11",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-11",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-12",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-12",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-12",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-12",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-12",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-13",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-13",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-14",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-14",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-14",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R3-15",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-15",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-15",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-15",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-15",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-16",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-16",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-16",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-16",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-16",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-17",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-17",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-18",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-18",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-18",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R3-19",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-19",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-19",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-19",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-19",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-20",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-20",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-20",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-20",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-20",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-21",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-21",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-22",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-22",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-22",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R3-23",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-23",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-23",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-23",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-23",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-24",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-24",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-24",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R3-24",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R3-24",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R3-25",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-25",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-26",
   "groupCode": "EL-1R3"
  },
  {
   "studentId": "1R3-26",
   "groupCode": "MA-1R3"
  },
  {
   "studentId": "1R3-26",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-01",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-01",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-01",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-01",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-01",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-02",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-02",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-02",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-02",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-02",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-03",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-03",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-04",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-04",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-04",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-05",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-05",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-05",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-05",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-05",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-06",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-06",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-06",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-06",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-06",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-07",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-07",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-08",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-08",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-08",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-09",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-09",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-09",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-09",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-09",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-10",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-10",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-10",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-10",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-10",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-11",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-11",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-12",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-12",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-12",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-13",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-13",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-13",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-13",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-13",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-14",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-14",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-14",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-14",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-14",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-15",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-15",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-16",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-16",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-16",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-17",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-17",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-17",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-17",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-17",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-18",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-18",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-18",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-18",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-18",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-19",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-19",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-20",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-20",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-20",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-21",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-21",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-21",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-21",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-21",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-22",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-22",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-22",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-22",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-22",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-23",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-23",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-24",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-24",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-24",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R4-25",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-25",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-25",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-25",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-25",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R4-26",
   "groupCode": "EL-1R4"
  },
  {
   "studentId": "1R4-26",
   "groupCode": "MA-1R4"
  },
  {
   "studentId": "1R4-26",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R4-26",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R4-26",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-01",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-01",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-02",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-02",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-02",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R5-03",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-03",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-03",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-03",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-03",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-04",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-04",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-04",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-04",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-04",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-05",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-05",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-06",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-06",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-06",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R5-07",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-07",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-07",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-07",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-07",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-08",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-08",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-08",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-08",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-08",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-09",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-09",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-10",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-10",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-10",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R5-11",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-11",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-11",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-11",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-11",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-12",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-12",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-12",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-12",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-12",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-13",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-13",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-14",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-14",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-14",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R5-15",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-15",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-15",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-15",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-15",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-16",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-16",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-16",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-16",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-16",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-17",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-17",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-18",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-18",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-18",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R5-19",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-19",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-19",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-19",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-19",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-20",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-20",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-20",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-20",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-20",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-21",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-21",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-22",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-22",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-22",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R5-23",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-23",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-23",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-23",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-23",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-24",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-24",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-24",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R5-24",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R5-24",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R5-25",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-25",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-26",
   "groupCode": "EL-1R5"
  },
  {
   "studentId": "1R5-26",
   "groupCode": "MA-1R5"
  },
  {
   "studentId": "1R5-26",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-01",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-01",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-01",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-01",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-01",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-02",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-02",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-02",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-02",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-02",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-03",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-03",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-04",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-04",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-04",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-05",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-05",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-05",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-05",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-05",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-06",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-06",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-06",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-06",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-06",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-07",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-07",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-08",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-08",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-08",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-09",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-09",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-09",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-09",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-09",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-10",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-10",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-10",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-10",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-10",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-11",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-11",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-12",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-12",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-12",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-13",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-13",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-13",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-13",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-13",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-14",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-14",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-14",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-14",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-14",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-15",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-15",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-16",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-16",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-16",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-17",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-17",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-17",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-17",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-17",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-18",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-18",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-18",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-18",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-18",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-19",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-19",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-20",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-20",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-20",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-21",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-21",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-21",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-21",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-21",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-22",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-22",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-22",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-22",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-22",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-23",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-23",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-24",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-24",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-24",
   "groupCode": "GEOG-G2"
  },
  {
   "studentId": "1R6-25",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-25",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-25",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-25",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-25",
   "groupCode": "LIT-G3"
  },
  {
   "studentId": "1R6-26",
   "groupCode": "EL-1R6"
  },
  {
   "studentId": "1R6-26",
   "groupCode": "MA-1R6"
  },
  {
   "studentId": "1R6-26",
   "groupCode": "SCI-G3"
  },
  {
   "studentId": "1R6-26",
   "groupCode": "HIST-G3"
  },
  {
   "studentId": "1R6-26",
   "groupCode": "LIT-G3"
  }
 ],
 "subjectKeys": [
  "TG",
  "EL",
  "MT",
  "HMT",
  "MA",
  "SCI",
  "HIST",
  "GEOG",
  "LIT"
 ]
};
