// Auto-generated by admin.html — do not edit by hand.
window.NAMELIST_DATA = {
 "savedAt": "2026-08-03T06:23:25.647Z",
 "students": [
  {
   "id": "S02601",
   "name": "Aiden Tan",
   "class": "4A",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02602",
   "name": "Brenda Teo",
   "class": "4A",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02603",
   "name": "Clarissa Nair",
   "class": "4A",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02604",
   "name": "Darren Wong",
   "class": "4A",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02605",
   "name": "Elena Chen",
   "class": "4A",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02606",
   "name": "Farhan Tan",
   "class": "4A",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02607",
   "name": "Grace Teo",
   "class": "4A",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02608",
   "name": "Hakim Nair",
   "class": "4A",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02609",
   "name": "Iris Wong",
   "class": "4A",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02610",
   "name": "Jun Jie Chen",
   "class": "4A",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02611",
   "name": "Kavya Tan",
   "class": "4A",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02612",
   "name": "Liang Teo",
   "class": "4A",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02613",
   "name": "Mei Ling Nair",
   "class": "4A",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02614",
   "name": "Nadia Wong",
   "class": "4A",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02615",
   "name": "Owen Chen",
   "class": "4A",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02616",
   "name": "Priya Tan",
   "class": "4A",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02617",
   "name": "Qi Wen Teo",
   "class": "4A",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02618",
   "name": "Ryan Nair",
   "class": "4A",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02619",
   "name": "Siti Wong",
   "class": "4A",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02620",
   "name": "Timothy Chen",
   "class": "4A",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02621",
   "name": "Uma Tan",
   "class": "4A",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02622",
   "name": "Vernon Teo",
   "class": "4A",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02623",
   "name": "Wei Ting Nair",
   "class": "4A",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02624",
   "name": "Xin Yi Wong",
   "class": "4A",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02625",
   "name": "Yusof Chen",
   "class": "4A",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02626",
   "name": "Zoe Tan",
   "class": "4A",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02627",
   "name": "Aiden Teo",
   "class": "4A",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02628",
   "name": "Brenda Nair",
   "class": "4A",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02629",
   "name": "Clarissa Nair",
   "class": "4B",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02630",
   "name": "Darren Wong",
   "class": "4B",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02631",
   "name": "Elena Chen",
   "class": "4B",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02632",
   "name": "Farhan Tan",
   "class": "4B",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02633",
   "name": "Grace Teo",
   "class": "4B",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02634",
   "name": "Hakim Nair",
   "class": "4B",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02635",
   "name": "Iris Wong",
   "class": "4B",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02636",
   "name": "Jun Jie Chen",
   "class": "4B",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02637",
   "name": "Kavya Tan",
   "class": "4B",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02638",
   "name": "Liang Teo",
   "class": "4B",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02639",
   "name": "Mei Ling Nair",
   "class": "4B",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02640",
   "name": "Nadia Wong",
   "class": "4B",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02641",
   "name": "Owen Chen",
   "class": "4B",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02642",
   "name": "Priya Tan",
   "class": "4B",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02643",
   "name": "Qi Wen Teo",
   "class": "4B",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02644",
   "name": "Ryan Nair",
   "class": "4B",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02645",
   "name": "Siti Wong",
   "class": "4B",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02646",
   "name": "Timothy Chen",
   "class": "4B",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02647",
   "name": "Uma Tan",
   "class": "4B",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02648",
   "name": "Vernon Teo",
   "class": "4B",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02649",
   "name": "Wei Ting Nair",
   "class": "4B",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02650",
   "name": "Xin Yi Wong",
   "class": "4B",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02651",
   "name": "Yusof Chen",
   "class": "4B",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02652",
   "name": "Zoe Tan",
   "class": "4B",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02653",
   "name": "Aiden Teo",
   "class": "4B",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02654",
   "name": "Brenda Nair",
   "class": "4B",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02655",
   "name": "Clarissa Wong",
   "class": "4B",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02656",
   "name": "Darren Chen",
   "class": "4B",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02657",
   "name": "Elena Chen",
   "class": "4C",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02658",
   "name": "Farhan Tan",
   "class": "4C",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02659",
   "name": "Grace Teo",
   "class": "4C",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02660",
   "name": "Hakim Nair",
   "class": "4C",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02661",
   "name": "Iris Wong",
   "class": "4C",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02662",
   "name": "Jun Jie Chen",
   "class": "4C",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02663",
   "name": "Kavya Tan",
   "class": "4C",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02664",
   "name": "Liang Teo",
   "class": "4C",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02665",
   "name": "Mei Ling Nair",
   "class": "4C",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02666",
   "name": "Nadia Wong",
   "class": "4C",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02667",
   "name": "Owen Chen",
   "class": "4C",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02668",
   "name": "Priya Tan",
   "class": "4C",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02669",
   "name": "Qi Wen Teo",
   "class": "4C",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02670",
   "name": "Ryan Nair",
   "class": "4C",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02671",
   "name": "Siti Wong",
   "class": "4C",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02672",
   "name": "Timothy Chen",
   "class": "4C",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02673",
   "name": "Uma Tan",
   "class": "4C",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02674",
   "name": "Vernon Teo",
   "class": "4C",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02675",
   "name": "Wei Ting Nair",
   "class": "4C",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02676",
   "name": "Xin Yi Wong",
   "class": "4C",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02677",
   "name": "Yusof Chen",
   "class": "4C",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02678",
   "name": "Zoe Tan",
   "class": "4C",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02679",
   "name": "Aiden Teo",
   "class": "4C",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02680",
   "name": "Brenda Nair",
   "class": "4C",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02681",
   "name": "Clarissa Wong",
   "class": "4C",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02682",
   "name": "Darren Chen",
   "class": "4C",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02683",
   "name": "Elena Tan",
   "class": "4C",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02684",
   "name": "Farhan Teo",
   "class": "4C",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02685",
   "name": "Grace Teo",
   "class": "4D",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02686",
   "name": "Hakim Nair",
   "class": "4D",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02687",
   "name": "Iris Wong",
   "class": "4D",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02688",
   "name": "Jun Jie Chen",
   "class": "4D",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02689",
   "name": "Kavya Tan",
   "class": "4D",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02690",
   "name": "Liang Teo",
   "class": "4D",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02691",
   "name": "Mei Ling Nair",
   "class": "4D",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02692",
   "name": "Nadia Wong",
   "class": "4D",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02693",
   "name": "Owen Chen",
   "class": "4D",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02694",
   "name": "Priya Tan",
   "class": "4D",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02695",
   "name": "Qi Wen Teo",
   "class": "4D",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02696",
   "name": "Ryan Nair",
   "class": "4D",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02697",
   "name": "Siti Wong",
   "class": "4D",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02698",
   "name": "Timothy Chen",
   "class": "4D",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02699",
   "name": "Uma Tan",
   "class": "4D",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02700",
   "name": "Vernon Teo",
   "class": "4D",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02701",
   "name": "Wei Ting Nair",
   "class": "4D",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02702",
   "name": "Xin Yi Wong",
   "class": "4D",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02703",
   "name": "Yusof Chen",
   "class": "4D",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02704",
   "name": "Zoe Tan",
   "class": "4D",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02705",
   "name": "Aiden Teo",
   "class": "4D",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02706",
   "name": "Brenda Nair",
   "class": "4D",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02707",
   "name": "Clarissa Wong",
   "class": "4D",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02708",
   "name": "Darren Chen",
   "class": "4D",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02709",
   "name": "Elena Tan",
   "class": "4D",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02710",
   "name": "Farhan Teo",
   "class": "4D",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02711",
   "name": "Grace Nair",
   "class": "4D",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02712",
   "name": "Hakim Wong",
   "class": "4D",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02713",
   "name": "Iris Wong",
   "class": "4E",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02714",
   "name": "Jun Jie Chen",
   "class": "4E",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02715",
   "name": "Kavya Tan",
   "class": "4E",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02716",
   "name": "Liang Teo",
   "class": "4E",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02717",
   "name": "Mei Ling Nair",
   "class": "4E",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02718",
   "name": "Nadia Wong",
   "class": "4E",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02719",
   "name": "Owen Chen",
   "class": "4E",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02720",
   "name": "Priya Tan",
   "class": "4E",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02721",
   "name": "Qi Wen Teo",
   "class": "4E",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02722",
   "name": "Ryan Nair",
   "class": "4E",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02723",
   "name": "Siti Wong",
   "class": "4E",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02724",
   "name": "Timothy Chen",
   "class": "4E",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02725",
   "name": "Uma Tan",
   "class": "4E",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02726",
   "name": "Vernon Teo",
   "class": "4E",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02727",
   "name": "Wei Ting Nair",
   "class": "4E",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02728",
   "name": "Xin Yi Wong",
   "class": "4E",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02729",
   "name": "Yusof Chen",
   "class": "4E",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02730",
   "name": "Zoe Tan",
   "class": "4E",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02731",
   "name": "Aiden Teo",
   "class": "4E",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02732",
   "name": "Brenda Nair",
   "class": "4E",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02733",
   "name": "Clarissa Wong",
   "class": "4E",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02734",
   "name": "Darren Chen",
   "class": "4E",
   "combination": "Physics / Chemistry / Biology"
  },
  {
   "id": "S02735",
   "name": "Elena Tan",
   "class": "4E",
   "combination": "Chemistry / Biology / Geography"
  },
  {
   "id": "S02736",
   "name": "Farhan Teo",
   "class": "4E",
   "combination": "Physics / Chemistry / Literature"
  },
  {
   "id": "S02737",
   "name": "Grace Nair",
   "class": "4E",
   "combination": "Chemistry / Biology / History"
  },
  {
   "id": "S02738",
   "name": "Hakim Wong",
   "class": "4E",
   "combination": "Geography / History / Literature"
  },
  {
   "id": "S02739",
   "name": "Iris Chen",
   "class": "4E",
   "combination": "Physics / Chemistry / Geography"
  },
  {
   "id": "S02740",
   "name": "Jun Jie Tan",
   "class": "4E",
   "combination": "Physics / Chemistry / Biology"
  }
 ],
 "groups": [
  {
   "code": "EL-4A",
   "name": "English 4A",
   "subject": "English Language",
   "teacher": "Mrs Lim Bee Leng"
  },
  {
   "code": "MA-4A",
   "name": "Mathematics 4A",
   "subject": "Mathematics",
   "teacher": "Mr Rajesh Kumar"
  },
  {
   "code": "EL-4B",
   "name": "English 4B",
   "subject": "English Language",
   "teacher": "Mr Daniel Tan"
  },
  {
   "code": "MA-4B",
   "name": "Mathematics 4B",
   "subject": "Mathematics",
   "teacher": "Mdm Halimah Yusof"
  },
  {
   "code": "EL-4C",
   "name": "English 4C",
   "subject": "English Language",
   "teacher": "Ms Nur Aisyah"
  },
  {
   "code": "MA-4C",
   "name": "Mathematics 4C",
   "subject": "Mathematics",
   "teacher": "Ms Serene Goh"
  },
  {
   "code": "EL-4D",
   "name": "English 4D",
   "subject": "English Language",
   "teacher": "Mrs Grace Chua"
  },
  {
   "code": "MA-4D",
   "name": "Mathematics 4D",
   "subject": "Mathematics",
   "teacher": "Mr Alvin Ong"
  },
  {
   "code": "EL-4E",
   "name": "English 4E",
   "subject": "English Language",
   "teacher": "Mr Marcus Lee"
  },
  {
   "code": "MA-4E",
   "name": "Mathematics 4E",
   "subject": "Mathematics",
   "teacher": "Mrs Doris Koh"
  },
  {
   "code": "PHY-1",
   "name": "Physics 1",
   "subject": "Physics",
   "teacher": "Mr Benjamin Teo"
  },
  {
   "code": "PHY-2",
   "name": "Physics 2",
   "subject": "Physics",
   "teacher": "Ms Cheryl Ng"
  },
  {
   "code": "CHEM-1",
   "name": "Chemistry 1",
   "subject": "Chemistry",
   "teacher": "Mrs Angela Wong"
  },
  {
   "code": "CHEM-2",
   "name": "Chemistry 2",
   "subject": "Chemistry",
   "teacher": "Mr Faizal Ismail"
  },
  {
   "code": "BIO-1",
   "name": "Biology 1",
   "subject": "Biology",
   "teacher": "Dr Sarah Loh"
  },
  {
   "code": "GEO-1",
   "name": "Geography 1",
   "subject": "Geography",
   "teacher": "Mr Kenneth Sim"
  },
  {
   "code": "HIST-1",
   "name": "History 1",
   "subject": "History",
   "teacher": "Ms Priyanka Nair"
  },
  {
   "code": "LIT-1",
   "name": "Literature 1",
   "subject": "Literature",
   "teacher": "Mrs Evelyn Phua"
  }
 ],
 "memberships": [
  {
   "studentId": "S02601",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02601",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02601",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02601",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02601",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02602",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02602",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02602",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02602",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02602",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02603",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02603",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02603",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02603",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02603",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02604",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02604",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02604",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02604",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02604",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02605",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02605",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02605",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02605",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02605",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02606",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02606",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02606",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02606",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02606",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02607",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02607",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02607",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02607",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02607",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02608",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02608",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02608",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02608",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02608",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02609",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02609",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02609",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02609",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02609",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02610",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02610",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02610",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02610",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02610",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02611",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02611",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02611",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02611",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02611",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02612",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02612",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02612",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02612",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02612",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02613",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02613",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02613",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02613",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02613",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02614",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02614",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02614",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02614",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02614",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02615",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02615",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02615",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02615",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02615",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02616",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02616",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02616",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02616",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02616",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02617",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02617",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02617",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02617",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02617",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02618",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02618",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02618",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02618",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02618",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02619",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02619",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02619",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02619",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02619",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02620",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02620",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02620",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02620",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02620",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02621",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02621",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02621",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02621",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02621",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02622",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02622",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02622",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02622",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02622",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02623",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02623",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02623",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02623",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02623",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02624",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02624",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02624",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02624",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02624",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02625",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02625",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02625",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02625",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02625",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02626",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02626",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02626",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02626",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02626",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02627",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02627",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02627",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02627",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02627",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02628",
   "groupCode": "EL-4A"
  },
  {
   "studentId": "S02628",
   "groupCode": "MA-4A"
  },
  {
   "studentId": "S02628",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02628",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02628",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02629",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02629",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02629",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02629",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02629",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02630",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02630",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02630",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02630",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02630",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02631",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02631",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02631",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02631",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02631",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02632",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02632",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02632",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02632",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02632",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02633",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02633",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02633",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02633",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02633",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02634",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02634",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02634",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02634",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02634",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02635",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02635",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02635",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02635",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02635",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02636",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02636",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02636",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02636",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02636",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02637",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02637",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02637",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02637",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02637",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02638",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02638",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02638",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02638",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02638",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02639",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02639",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02639",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02639",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02639",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02640",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02640",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02640",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02640",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02640",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02641",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02641",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02641",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02641",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02641",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02642",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02642",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02642",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02642",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02642",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02643",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02643",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02643",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02643",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02643",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02644",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02644",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02644",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02644",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02644",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02645",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02645",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02645",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02645",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02645",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02646",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02646",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02646",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02646",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02646",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02647",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02647",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02647",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02647",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02647",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02648",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02648",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02648",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02648",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02648",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02649",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02649",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02649",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02649",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02649",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02650",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02650",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02650",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02650",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02650",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02651",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02651",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02651",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02651",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02651",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02652",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02652",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02652",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02652",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02652",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02653",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02653",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02653",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02653",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02653",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02654",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02654",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02654",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02654",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02654",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02655",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02655",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02655",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02655",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02655",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02656",
   "groupCode": "EL-4B"
  },
  {
   "studentId": "S02656",
   "groupCode": "MA-4B"
  },
  {
   "studentId": "S02656",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02656",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02656",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02657",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02657",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02657",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02657",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02657",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02658",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02658",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02658",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02658",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02658",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02659",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02659",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02659",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02659",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02659",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02660",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02660",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02660",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02660",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02660",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02661",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02661",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02661",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02661",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02661",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02662",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02662",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02662",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02662",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02662",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02663",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02663",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02663",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02663",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02663",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02664",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02664",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02664",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02664",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02664",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02665",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02665",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02665",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02665",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02665",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02666",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02666",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02666",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02666",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02666",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02667",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02667",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02667",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02667",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02667",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02668",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02668",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02668",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02668",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02668",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02669",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02669",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02669",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02669",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02669",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02670",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02670",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02670",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02670",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02670",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02671",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02671",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02671",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02671",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02671",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02672",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02672",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02672",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02672",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02672",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02673",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02673",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02673",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02673",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02673",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02674",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02674",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02674",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02674",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02674",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02675",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02675",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02675",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02675",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02675",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02676",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02676",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02676",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02676",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02676",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02677",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02677",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02677",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02677",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02677",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02678",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02678",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02678",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02678",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02678",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02679",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02679",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02679",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02679",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02679",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02680",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02680",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02680",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02680",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02680",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02681",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02681",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02681",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02681",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02681",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02682",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02682",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02682",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02682",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02682",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02683",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02683",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02683",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02683",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02683",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02684",
   "groupCode": "EL-4C"
  },
  {
   "studentId": "S02684",
   "groupCode": "MA-4C"
  },
  {
   "studentId": "S02684",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02684",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02684",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02685",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02685",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02685",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02685",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02685",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02686",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02686",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02686",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02686",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02686",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02687",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02687",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02687",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02687",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02687",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02688",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02688",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02688",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02688",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02688",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02689",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02689",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02689",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02689",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02689",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02690",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02690",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02690",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02690",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02690",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02691",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02691",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02691",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02691",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02691",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02692",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02692",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02692",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02692",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02692",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02693",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02693",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02693",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02693",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02693",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02694",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02694",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02694",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02694",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02694",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02695",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02695",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02695",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02695",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02695",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02696",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02696",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02696",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02696",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02696",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02697",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02697",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02697",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02697",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02697",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02698",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02698",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02698",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02698",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02698",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02699",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02699",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02699",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02699",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02699",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02700",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02700",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02700",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02700",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02700",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02701",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02701",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02701",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02701",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02701",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02702",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02702",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02702",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02702",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02702",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02703",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02703",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02703",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02703",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02703",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02704",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02704",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02704",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02704",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02704",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02705",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02705",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02705",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02705",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02705",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02706",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02706",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02706",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02706",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02706",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02707",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02707",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02707",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02707",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02707",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02708",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02708",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02708",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02708",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02708",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02709",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02709",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02709",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02709",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02709",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02710",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02710",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02710",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02710",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02710",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02711",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02711",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02711",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02711",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02711",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02712",
   "groupCode": "EL-4D"
  },
  {
   "studentId": "S02712",
   "groupCode": "MA-4D"
  },
  {
   "studentId": "S02712",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02712",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02712",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02713",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02713",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02713",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02713",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02713",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02714",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02714",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02714",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02714",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02714",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02715",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02715",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02715",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02715",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02715",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02716",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02716",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02716",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02716",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02716",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02717",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02717",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02717",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02717",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02717",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02718",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02718",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02718",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02718",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02718",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02719",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02719",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02719",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02719",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02719",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02720",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02720",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02720",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02720",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02720",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02721",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02721",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02721",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02721",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02721",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02722",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02722",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02722",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02722",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02722",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02723",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02723",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02723",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02723",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02723",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02724",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02724",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02724",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02724",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02724",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02725",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02725",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02725",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02725",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02725",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02726",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02726",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02726",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02726",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02726",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02727",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02727",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02727",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02727",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02727",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02728",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02728",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02728",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02728",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02728",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02729",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02729",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02729",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02729",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02729",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02730",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02730",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02730",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02730",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02730",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02731",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02731",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02731",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02731",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02731",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02732",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02732",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02732",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02732",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02732",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02733",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02733",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02733",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02733",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02733",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02734",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02734",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02734",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02734",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02734",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02735",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02735",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02735",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02735",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02735",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02736",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02736",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02736",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02736",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02736",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02737",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02737",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02737",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02737",
   "groupCode": "BIO-1"
  },
  {
   "studentId": "S02737",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02738",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02738",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02738",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02738",
   "groupCode": "HIST-1"
  },
  {
   "studentId": "S02738",
   "groupCode": "LIT-1"
  },
  {
   "studentId": "S02739",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02739",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02739",
   "groupCode": "PHY-1"
  },
  {
   "studentId": "S02739",
   "groupCode": "CHEM-1"
  },
  {
   "studentId": "S02739",
   "groupCode": "GEO-1"
  },
  {
   "studentId": "S02740",
   "groupCode": "EL-4E"
  },
  {
   "studentId": "S02740",
   "groupCode": "MA-4E"
  },
  {
   "studentId": "S02740",
   "groupCode": "PHY-2"
  },
  {
   "studentId": "S02740",
   "groupCode": "CHEM-2"
  },
  {
   "studentId": "S02740",
   "groupCode": "BIO-1"
  }
 ]
};
